---
format:
    pdf:
        fig-dpi: 300
echo: false
highlight-style: github
monofont: Fira Code
warning: false
---

```{r}
#| include: false

library(tidyverse)
library(coda)
library(glue)
library(kableExtra)

samples <- read_csv("samples.csv") |>
    rename(Iteration = `...1`) |>
    pivot_longer(starts_with("birth_rate"),
        names_to = "Parameter",
        values_to = "Sample"
    ) |>
    mutate(tree = factor(tree))

truth <- tibble(
    Parameter = c("birth_rate1", "birth_rate2"),
    Truth = c(1, 4)
)
```

## Traceplots

```{r}
#| fig-height: 6

ggplot(samples, aes(Iteration, Sample, color = tree)) +
    geom_line() +
    facet_wrap(vars(Parameter), ncol = 1)
```

## Summaries

```{r}
samples |>
    group_by(Parameter, tree) |>
    summarise(
        n = n(),
        ESS = effectiveSize(Sample),
        quantile_025 = quantile(Sample, 0.025),
        median = median(Sample),
        quantile_975 = quantile(Sample, 0.975),
    ) |>
    left_join(truth, by = "Parameter") |>
    mutate(
        `Relative error` = abs((median - Truth) / Truth),
        Coverage = quantile_025 <= Truth & Truth <= quantile_975
    ) |>
    group_by(Parameter) |>
    summarise(
        n = sum(n),
        ESS = sum(ESS) |> round(),
        `Relative error` = mean(`Relative error`),
        Coverage = glue("{100*mean(Coverage)}%")
    ) |>
    kbl(booktabs = TRUE)
```

\pagebreak

## Densities

```{r}
#| fig-height: 7

left_join(samples, truth, by = "Parameter") |>
    filter(tree %in% 1:5) |>
    ggplot() +
    stat_function(
        aes(fill = "Prior"),
        fun = dlnorm,
        args = list(meanlog = 1.5, sdlog = 1),
        geom = "area",
        alpha = 0.8
    ) +
    geom_histogram(
        aes(x = Sample, y = after_stat(density), fill = "Posterior"),
        alpha = 0.8
    ) +
    geom_vline(aes(xintercept = Truth),
        color = "red",
        linewidth = 1.5,
        linetype = "dashed"
    ) +
    lims(x = c(0, 6)) +
    scale_fill_manual(
        name = "",
        values = c("Prior" = "grey", "Posterior" = "steelblue")
    ) +
    facet_grid(paste("Tree", tree) ~ Parameter) +
    theme(legend.position = "bottom")
```

