---
format:
    pdf:
        fig-dpi: 300
echo: false
highlight-style: github
monofont: Fira Code
warning: false
---

```{r}
#| include: false

library(tidyverse)
library(coda)
library(glue)
library(kableExtra)

samples <- read_csv("samples.csv") |>
    rename(Iteration = `...1`) |>
    pivot_longer(c("birth_rate1", "birth_rate2", "birth_rate3", "birth_rate4", "death_rate"),
        names_to = "Parameter",
        values_to = "Sample"
    )

truth <- tibble(
    Parameter = c("birth_rate1", "birth_rate2", "birth_rate3", "birth_rate4", "death_rate"),
    Truth = c(1, 1.5, 2, 2.5, 1.3)
)
```

## Posterior median sampling distributions

```{r}
#| fig-height: 6

samples |>
    group_by(run, Parameter) |>
    summarise(Estimate = median(Sample)) |>
    left_join(truth, by = "Parameter") |>
    ggplot() +
    geom_histogram(
        aes(x = Estimate, y = after_stat(density), fill = "Sampling distribution")
    ) +
    geom_vline(aes(xintercept = Truth),
        color = "red",
        linewidth = 1
    ) +
    scale_fill_manual(
        name = "",
        values = c("Sampling distribution" = "steelblue")
    ) +
    facet_wrap(vars(Parameter), ncol = 2, scales = "free") +
    xlab("Estimate") +
    theme(legend.position = "bottom")
```

\pagebreak

## Traceplots (full)

```{r}
#| fig-height: 6

left_join(samples, truth, by = "Parameter") |>
    filter(run == 1) |>
    ggplot(aes(Iteration, Sample)) +
    geom_line() +
    geom_hline(aes(yintercept = Truth, color = "Truth")) +
    facet_wrap(vars(Parameter), ncol = 1, scales = "free")
```

## Traceplots (after burn-in)

```{r}
#| fig-height: 6

left_join(samples, truth, by = "Parameter") |>
    filter(Iteration > 2500 & run == 1) |>
    ggplot(aes(Iteration, Sample)) +
    geom_line() +
    geom_hline(aes(yintercept = Truth, color = "Truth")) +
    facet_wrap(vars(Parameter), ncol = 1, scales = "free")
```

\pagebreak

## Densities

```{r}
#| fig-height: 6

left_join(samples, truth, by = "Parameter") |>
    filter(run == 1) |>
    ggplot() +
    geom_histogram(
        aes(x = Sample, y = after_stat(density), fill = "Posterior")
    ) +
    geom_vline(aes(xintercept = Truth),
        color = "red",
        linewidth = 1
    ) +
    scale_fill_manual(
        name = "",
        values = c("Posterior" = "steelblue")
    ) +
    facet_wrap(vars(Parameter), ncol = 2, scales = "free") +
    scale_x_sqrt() +
    xlab("Sample (on sqrt scale)") +
    theme(legend.position = "bottom")
```

\pagebreak

## Summaries

```{r}
samples |>
    filter(run == 1) |>
    group_by(Parameter) |>
    summarise(
        n = n(),
        ESS = effectiveSize(Sample) |> round(),
        `Acceptance` = mean(Sample[-1] != Sample[1:length(Sample) - 1]) |> round(2),
        `Q 25%` = quantile(Sample, 0.025) |> round(2),
        Median = median(Sample) |> round(2),
        `Q 75%` = quantile(Sample, 0.975) |> round(2),
    ) |>
    left_join(truth, by = "Parameter") |>
    mutate(
        `Relative error` = abs((Median - Truth) / Truth) |> round(2)
    ) |>
    kbl(booktabs = TRUE)
```