name: Docs build and deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install
        run: make install

      - name: Build 🔧
        run: |
          make docs
        env:
          QT_QPA_PLATFORM: offscreen
          XDG_RUNTIME_DIR: /tmp/runtime-runner
          MPLBACKEND: agg

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: docs # The branch the action should deploy to.
          folder: docs/_build/html # The folder the action should deploy.
